### ISSUE TITLE
Arr::key() is inconsistent with string parameters.

### ISSUE THREAD

**Issue by jmwebservices** [JBZoo/Utils#19]
`Arr::key()` returns inconsistent results if the passed `$array` parameter is a `string`.
```
// expect '01' but returns '0'
Arr::key( 0, '01', true );

// returns null as expected
// but should return '1' to be consistent with the previous example
Arr::key( 1, '01', true );
```
The inconsistency is due to `Arr::key()` casting the `$array` parameter for `array_key_exists()` but it returns the value of the *un*casted parameter.

**Comment by SmetDenis** [comment]
Hi,

Thank you for your suggestion and advice.

 Sorry, I would prefer to use the second argument as array variable only.

 Also, I marked the function as deprecated (see version `dev-master` or  `4.0.x-dev`). Several years ago PHP doesn't work properly works with arrays. Now we have nice operators `?:` and `??`.
