### ISSUE TITLE
undefined function JBZoo\Data\data()

### ISSUE THREAD

**Issue by canc** [JBZoo/Utils#22]
Hi,
I'm getting this error when i try to use Url::current()

Fatal error: Uncaught Error: Call to undefined function JBZoo\Data\data() in /Applications/MAMP/htdocs/inc/JBZoo/Utils/Url.php:162 Stack trace: #0 /Applications/MAMP/htdocs/inc/JBZoo/Utils/Url.php(115): JBZoo\Utils\Url::root(false) #1 /Applications/MAMP/htdocs/a/index.php(11): JBZoo\Utils\Url::current() #2 {main} thrown in /Applications/MAMP/htdocs/inc/JBZoo/Utils/Url.php on line 162

Also throws an error on Url::buildAll() at Url.php on line 243

![Screen Shot 2019-06-22 at 14 59 58](https://user-images.githubusercontent.com/8061037/59963631-9988e380-94fe-11e9-8e12-7b33e453d574.png)

**Comment by SmetDenis** [comment]
Hi.

Try to import it.
```
use function JBZoo\Data\data;
```

**Comment by canc** [comment]
Thanks for your reply,
It's already being imported by the class but it says "undefined namespace"

![Screen Shot 2019-06-26 at 16 27 14](https://user-images.githubusercontent.com/8061037/60183616-4df07580-982f-11e9-8dda-505a3ce1f079.png)

**Comment by SmetDenis** [comment]
Are you sure that package `jbzoo/data` is included in your `composer.json`?

**Comment by canc** [comment]
oh okay, that was the problem. didn't notice that a bit :) 
thanks for your help!
